// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: delete_job.proto

package com.mogujie.jarvis.protocol;

public final class DeleteJobProtos {
  private DeleteJobProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RestServerDeleteJobRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RestServerDeleteJobRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 job_id = 1;</code>
     */
    boolean hasJobId();
    /**
     * <code>required int64 job_id = 1;</code>
     */
    long getJobId();
  }
  /**
   * Protobuf type {@code RestServerDeleteJobRequest}
   */
  public static final class RestServerDeleteJobRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RestServerDeleteJobRequest)
      RestServerDeleteJobRequestOrBuilder {
    // Use RestServerDeleteJobRequest.newBuilder() to construct.
    private RestServerDeleteJobRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RestServerDeleteJobRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RestServerDeleteJobRequest defaultInstance;
    public static RestServerDeleteJobRequest getDefaultInstance() {
      return defaultInstance;
    }

    public RestServerDeleteJobRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RestServerDeleteJobRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              jobId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mogujie.jarvis.protocol.DeleteJobProtos.internal_static_RestServerDeleteJobRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mogujie.jarvis.protocol.DeleteJobProtos.internal_static_RestServerDeleteJobRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest.class, com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<RestServerDeleteJobRequest> PARSER =
        new com.google.protobuf.AbstractParser<RestServerDeleteJobRequest>() {
      public RestServerDeleteJobRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RestServerDeleteJobRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RestServerDeleteJobRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int JOB_ID_FIELD_NUMBER = 1;
    private long jobId_;
    /**
     * <code>required int64 job_id = 1;</code>
     */
    public boolean hasJobId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 job_id = 1;</code>
     */
    public long getJobId() {
      return jobId_;
    }

    private void initFields() {
      jobId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasJobId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, jobId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, jobId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RestServerDeleteJobRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RestServerDeleteJobRequest)
        com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mogujie.jarvis.protocol.DeleteJobProtos.internal_static_RestServerDeleteJobRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mogujie.jarvis.protocol.DeleteJobProtos.internal_static_RestServerDeleteJobRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest.class, com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest.Builder.class);
      }

      // Construct using com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        jobId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mogujie.jarvis.protocol.DeleteJobProtos.internal_static_RestServerDeleteJobRequest_descriptor;
      }

      public com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest getDefaultInstanceForType() {
        return com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest.getDefaultInstance();
      }

      public com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest build() {
        com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest buildPartial() {
        com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest result = new com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.jobId_ = jobId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest) {
          return mergeFrom((com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest other) {
        if (other == com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest.getDefaultInstance()) return this;
        if (other.hasJobId()) {
          setJobId(other.getJobId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasJobId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mogujie.jarvis.protocol.DeleteJobProtos.RestServerDeleteJobRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long jobId_ ;
      /**
       * <code>required int64 job_id = 1;</code>
       */
      public boolean hasJobId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 job_id = 1;</code>
       */
      public long getJobId() {
        return jobId_;
      }
      /**
       * <code>required int64 job_id = 1;</code>
       */
      public Builder setJobId(long value) {
        bitField0_ |= 0x00000001;
        jobId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 job_id = 1;</code>
       */
      public Builder clearJobId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        jobId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RestServerDeleteJobRequest)
    }

    static {
      defaultInstance = new RestServerDeleteJobRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RestServerDeleteJobRequest)
  }

  public interface ServerDeleteJobResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ServerDeleteJobResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bool success = 1;</code>
     */
    boolean hasSuccess();
    /**
     * <code>required bool success = 1;</code>
     */
    boolean getSuccess();
  }
  /**
   * Protobuf type {@code ServerDeleteJobResponse}
   */
  public static final class ServerDeleteJobResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ServerDeleteJobResponse)
      ServerDeleteJobResponseOrBuilder {
    // Use ServerDeleteJobResponse.newBuilder() to construct.
    private ServerDeleteJobResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServerDeleteJobResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServerDeleteJobResponse defaultInstance;
    public static ServerDeleteJobResponse getDefaultInstance() {
      return defaultInstance;
    }

    public ServerDeleteJobResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServerDeleteJobResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              success_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mogujie.jarvis.protocol.DeleteJobProtos.internal_static_ServerDeleteJobResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mogujie.jarvis.protocol.DeleteJobProtos.internal_static_ServerDeleteJobResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse.class, com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<ServerDeleteJobResponse> PARSER =
        new com.google.protobuf.AbstractParser<ServerDeleteJobResponse>() {
      public ServerDeleteJobResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerDeleteJobResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServerDeleteJobResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>required bool success = 1;</code>
     */
    public boolean hasSuccess() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    private void initFields() {
      success_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSuccess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, success_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ServerDeleteJobResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ServerDeleteJobResponse)
        com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mogujie.jarvis.protocol.DeleteJobProtos.internal_static_ServerDeleteJobResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mogujie.jarvis.protocol.DeleteJobProtos.internal_static_ServerDeleteJobResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse.class, com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse.Builder.class);
      }

      // Construct using com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        success_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mogujie.jarvis.protocol.DeleteJobProtos.internal_static_ServerDeleteJobResponse_descriptor;
      }

      public com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse getDefaultInstanceForType() {
        return com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse.getDefaultInstance();
      }

      public com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse build() {
        com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse buildPartial() {
        com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse result = new com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.success_ = success_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse) {
          return mergeFrom((com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse other) {
        if (other == com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse.getDefaultInstance()) return this;
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSuccess()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mogujie.jarvis.protocol.DeleteJobProtos.ServerDeleteJobResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean success_ ;
      /**
       * <code>required bool success = 1;</code>
       */
      public boolean hasSuccess() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>required bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        bitField0_ |= 0x00000001;
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool success = 1;</code>
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ServerDeleteJobResponse)
    }

    static {
      defaultInstance = new ServerDeleteJobResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ServerDeleteJobResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RestServerDeleteJobRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RestServerDeleteJobRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerDeleteJobResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServerDeleteJobResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020delete_job.proto\",\n\032RestServerDeleteJo" +
      "bRequest\022\016\n\006job_id\030\001 \002(\003\"*\n\027ServerDelete" +
      "JobResponse\022\017\n\007success\030\001 \002(\010B.\n\033com.mogu" +
      "jie.jarvis.protocolB\017DeleteJobProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RestServerDeleteJobRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RestServerDeleteJobRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RestServerDeleteJobRequest_descriptor,
        new java.lang.String[] { "JobId", });
    internal_static_ServerDeleteJobResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ServerDeleteJobResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ServerDeleteJobResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
