// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remove_task.proto

package com.mogujie.jarvis.protocol;

public final class RemoveTaskProtos {
  private RemoveTaskProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RestServerRemoveTaskRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .AppAuth app_auth = 1;
    /**
     * <code>required .AppAuth app_auth = 1;</code>
     */
    boolean hasAppAuth();
    /**
     * <code>required .AppAuth app_auth = 1;</code>
     */
    com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth getAppAuth();
    /**
     * <code>required .AppAuth app_auth = 1;</code>
     */
    com.mogujie.jarvis.protocol.AppAuthProtos.AppAuthOrBuilder getAppAuthOrBuilder();

    // required int64 task_id = 2;
    /**
     * <code>required int64 task_id = 2;</code>
     */
    boolean hasTaskId();
    /**
     * <code>required int64 task_id = 2;</code>
     */
    long getTaskId();
  }
  /**
   * Protobuf type {@code RestServerRemoveTaskRequest}
   */
  public static final class RestServerRemoveTaskRequest extends
      com.google.protobuf.GeneratedMessage
      implements RestServerRemoveTaskRequestOrBuilder {
    // Use RestServerRemoveTaskRequest.newBuilder() to construct.
    private RestServerRemoveTaskRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RestServerRemoveTaskRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RestServerRemoveTaskRequest defaultInstance;
    public static RestServerRemoveTaskRequest getDefaultInstance() {
      return defaultInstance;
    }

    public RestServerRemoveTaskRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RestServerRemoveTaskRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = appAuth_.toBuilder();
              }
              appAuth_ = input.readMessage(com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(appAuth_);
                appAuth_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              taskId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mogujie.jarvis.protocol.RemoveTaskProtos.internal_static_RestServerRemoveTaskRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mogujie.jarvis.protocol.RemoveTaskProtos.internal_static_RestServerRemoveTaskRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest.class, com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<RestServerRemoveTaskRequest> PARSER =
        new com.google.protobuf.AbstractParser<RestServerRemoveTaskRequest>() {
      public RestServerRemoveTaskRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RestServerRemoveTaskRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RestServerRemoveTaskRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .AppAuth app_auth = 1;
    public static final int APP_AUTH_FIELD_NUMBER = 1;
    private com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth appAuth_;
    /**
     * <code>required .AppAuth app_auth = 1;</code>
     */
    public boolean hasAppAuth() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .AppAuth app_auth = 1;</code>
     */
    public com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth getAppAuth() {
      return appAuth_;
    }
    /**
     * <code>required .AppAuth app_auth = 1;</code>
     */
    public com.mogujie.jarvis.protocol.AppAuthProtos.AppAuthOrBuilder getAppAuthOrBuilder() {
      return appAuth_;
    }

    // required int64 task_id = 2;
    public static final int TASK_ID_FIELD_NUMBER = 2;
    private long taskId_;
    /**
     * <code>required int64 task_id = 2;</code>
     */
    public boolean hasTaskId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 task_id = 2;</code>
     */
    public long getTaskId() {
      return taskId_;
    }

    private void initFields() {
      appAuth_ = com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.getDefaultInstance();
      taskId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAppAuth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTaskId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getAppAuth().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, appAuth_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, taskId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, appAuth_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, taskId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RestServerRemoveTaskRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mogujie.jarvis.protocol.RemoveTaskProtos.internal_static_RestServerRemoveTaskRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mogujie.jarvis.protocol.RemoveTaskProtos.internal_static_RestServerRemoveTaskRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest.class, com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest.Builder.class);
      }

      // Construct using com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAppAuthFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (appAuthBuilder_ == null) {
          appAuth_ = com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.getDefaultInstance();
        } else {
          appAuthBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        taskId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mogujie.jarvis.protocol.RemoveTaskProtos.internal_static_RestServerRemoveTaskRequest_descriptor;
      }

      public com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest getDefaultInstanceForType() {
        return com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest.getDefaultInstance();
      }

      public com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest build() {
        com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest buildPartial() {
        com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest result = new com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (appAuthBuilder_ == null) {
          result.appAuth_ = appAuth_;
        } else {
          result.appAuth_ = appAuthBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.taskId_ = taskId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest) {
          return mergeFrom((com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest other) {
        if (other == com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest.getDefaultInstance()) return this;
        if (other.hasAppAuth()) {
          mergeAppAuth(other.getAppAuth());
        }
        if (other.hasTaskId()) {
          setTaskId(other.getTaskId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAppAuth()) {
          
          return false;
        }
        if (!hasTaskId()) {
          
          return false;
        }
        if (!getAppAuth().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mogujie.jarvis.protocol.RemoveTaskProtos.RestServerRemoveTaskRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .AppAuth app_auth = 1;
      private com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth appAuth_ = com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth, com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.Builder, com.mogujie.jarvis.protocol.AppAuthProtos.AppAuthOrBuilder> appAuthBuilder_;
      /**
       * <code>required .AppAuth app_auth = 1;</code>
       */
      public boolean hasAppAuth() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .AppAuth app_auth = 1;</code>
       */
      public com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth getAppAuth() {
        if (appAuthBuilder_ == null) {
          return appAuth_;
        } else {
          return appAuthBuilder_.getMessage();
        }
      }
      /**
       * <code>required .AppAuth app_auth = 1;</code>
       */
      public Builder setAppAuth(com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth value) {
        if (appAuthBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          appAuth_ = value;
          onChanged();
        } else {
          appAuthBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .AppAuth app_auth = 1;</code>
       */
      public Builder setAppAuth(
          com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.Builder builderForValue) {
        if (appAuthBuilder_ == null) {
          appAuth_ = builderForValue.build();
          onChanged();
        } else {
          appAuthBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .AppAuth app_auth = 1;</code>
       */
      public Builder mergeAppAuth(com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth value) {
        if (appAuthBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              appAuth_ != com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.getDefaultInstance()) {
            appAuth_ =
              com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.newBuilder(appAuth_).mergeFrom(value).buildPartial();
          } else {
            appAuth_ = value;
          }
          onChanged();
        } else {
          appAuthBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .AppAuth app_auth = 1;</code>
       */
      public Builder clearAppAuth() {
        if (appAuthBuilder_ == null) {
          appAuth_ = com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.getDefaultInstance();
          onChanged();
        } else {
          appAuthBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .AppAuth app_auth = 1;</code>
       */
      public com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.Builder getAppAuthBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getAppAuthFieldBuilder().getBuilder();
      }
      /**
       * <code>required .AppAuth app_auth = 1;</code>
       */
      public com.mogujie.jarvis.protocol.AppAuthProtos.AppAuthOrBuilder getAppAuthOrBuilder() {
        if (appAuthBuilder_ != null) {
          return appAuthBuilder_.getMessageOrBuilder();
        } else {
          return appAuth_;
        }
      }
      /**
       * <code>required .AppAuth app_auth = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth, com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.Builder, com.mogujie.jarvis.protocol.AppAuthProtos.AppAuthOrBuilder> 
          getAppAuthFieldBuilder() {
        if (appAuthBuilder_ == null) {
          appAuthBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth, com.mogujie.jarvis.protocol.AppAuthProtos.AppAuth.Builder, com.mogujie.jarvis.protocol.AppAuthProtos.AppAuthOrBuilder>(
                  appAuth_,
                  getParentForChildren(),
                  isClean());
          appAuth_ = null;
        }
        return appAuthBuilder_;
      }

      // required int64 task_id = 2;
      private long taskId_ ;
      /**
       * <code>required int64 task_id = 2;</code>
       */
      public boolean hasTaskId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 task_id = 2;</code>
       */
      public long getTaskId() {
        return taskId_;
      }
      /**
       * <code>required int64 task_id = 2;</code>
       */
      public Builder setTaskId(long value) {
        bitField0_ |= 0x00000002;
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 task_id = 2;</code>
       */
      public Builder clearTaskId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        taskId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RestServerRemoveTaskRequest)
    }

    static {
      defaultInstance = new RestServerRemoveTaskRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RestServerRemoveTaskRequest)
  }

  public interface ServerRemoveTaskResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool success = 1;
    /**
     * <code>required bool success = 1;</code>
     */
    boolean hasSuccess();
    /**
     * <code>required bool success = 1;</code>
     */
    boolean getSuccess();

    // optional string message = 2 [default = ""];
    /**
     * <code>optional string message = 2 [default = ""];</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 2 [default = ""];</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 2 [default = ""];</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code ServerRemoveTaskResponse}
   */
  public static final class ServerRemoveTaskResponse extends
      com.google.protobuf.GeneratedMessage
      implements ServerRemoveTaskResponseOrBuilder {
    // Use ServerRemoveTaskResponse.newBuilder() to construct.
    private ServerRemoveTaskResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServerRemoveTaskResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServerRemoveTaskResponse defaultInstance;
    public static ServerRemoveTaskResponse getDefaultInstance() {
      return defaultInstance;
    }

    public ServerRemoveTaskResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServerRemoveTaskResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              success_ = input.readBool();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              message_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mogujie.jarvis.protocol.RemoveTaskProtos.internal_static_ServerRemoveTaskResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mogujie.jarvis.protocol.RemoveTaskProtos.internal_static_ServerRemoveTaskResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse.class, com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<ServerRemoveTaskResponse> PARSER =
        new com.google.protobuf.AbstractParser<ServerRemoveTaskResponse>() {
      public ServerRemoveTaskResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerRemoveTaskResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServerRemoveTaskResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bool success = 1;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>required bool success = 1;</code>
     */
    public boolean hasSuccess() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    // optional string message = 2 [default = ""];
    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 2 [default = ""];</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string message = 2 [default = ""];</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 2 [default = ""];</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      success_ = false;
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSuccess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, success_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ServerRemoveTaskResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mogujie.jarvis.protocol.RemoveTaskProtos.internal_static_ServerRemoveTaskResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mogujie.jarvis.protocol.RemoveTaskProtos.internal_static_ServerRemoveTaskResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse.class, com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse.Builder.class);
      }

      // Construct using com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        success_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mogujie.jarvis.protocol.RemoveTaskProtos.internal_static_ServerRemoveTaskResponse_descriptor;
      }

      public com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse getDefaultInstanceForType() {
        return com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse.getDefaultInstance();
      }

      public com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse build() {
        com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse buildPartial() {
        com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse result = new com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.success_ = success_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse) {
          return mergeFrom((com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse other) {
        if (other == com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse.getDefaultInstance()) return this;
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000002;
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSuccess()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mogujie.jarvis.protocol.RemoveTaskProtos.ServerRemoveTaskResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool success = 1;
      private boolean success_ ;
      /**
       * <code>required bool success = 1;</code>
       */
      public boolean hasSuccess() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>required bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        bitField0_ |= 0x00000001;
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool success = 1;</code>
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        onChanged();
        return this;
      }

      // optional string message = 2 [default = ""];
      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 2 [default = ""];</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string message = 2 [default = ""];</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 2 [default = ""];</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 2 [default = ""];</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 2 [default = ""];</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 2 [default = ""];</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ServerRemoveTaskResponse)
    }

    static {
      defaultInstance = new ServerRemoveTaskResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ServerRemoveTaskResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RestServerRemoveTaskRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RestServerRemoveTaskRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerRemoveTaskResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServerRemoveTaskResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021remove_task.proto\032\016app_auth.proto\"J\n\033R" +
      "estServerRemoveTaskRequest\022\032\n\010app_auth\030\001" +
      " \002(\0132\010.AppAuth\022\017\n\007task_id\030\002 \002(\003\">\n\030Serve" +
      "rRemoveTaskResponse\022\017\n\007success\030\001 \002(\010\022\021\n\007" +
      "message\030\002 \001(\t:\000B/\n\033com.mogujie.jarvis.pr" +
      "otocolB\020RemoveTaskProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RestServerRemoveTaskRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RestServerRemoveTaskRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RestServerRemoveTaskRequest_descriptor,
              new java.lang.String[] { "AppAuth", "TaskId", });
          internal_static_ServerRemoveTaskResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ServerRemoveTaskResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ServerRemoveTaskResponse_descriptor,
              new java.lang.String[] { "Success", "Message", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.mogujie.jarvis.protocol.AppAuthProtos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
