// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report_task_progress.proto

package com.mogujie.jarvis.protocol;

public final class ReportTaskProgressProtos {
    private ReportTaskProgressProtos() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface WorkerReportTaskProgressRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:WorkerReportTaskProgressRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required string full_id = 1;</code>
         */
        boolean hasFullId();

        /**
         * <code>required string full_id = 1;</code>
         */
        java.lang.String getFullId();

        /**
         * <code>required string full_id = 1;</code>
         */
        com.google.protobuf.ByteString getFullIdBytes();

        /**
         * <code>required float progress = 2;</code>
         */
        boolean hasProgress();

        /**
         * <code>required float progress = 2;</code>
         */
        float getProgress();
    }

    /**
     * Protobuf type {@code WorkerReportTaskProgressRequest}
     */
    public static final class WorkerReportTaskProgressRequest extends com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:WorkerReportTaskProgressRequest)
            WorkerReportTaskProgressRequestOrBuilder {
        // Use WorkerReportTaskProgressRequest.newBuilder() to construct.
        private WorkerReportTaskProgressRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private WorkerReportTaskProgressRequest(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final WorkerReportTaskProgressRequest defaultInstance;

        public static WorkerReportTaskProgressRequest getDefaultInstance() {
            return defaultInstance;
        }

        public WorkerReportTaskProgressRequest getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private WorkerReportTaskProgressRequest(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            fullId_ = bs;
                            break;
                        }
                        case 21: {
                            bitField0_ |= 0x00000002;
                            progress_ = input.readFloat();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.mogujie.jarvis.protocol.ReportTaskProgressProtos.internal_static_WorkerReportTaskProgressRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.mogujie.jarvis.protocol.ReportTaskProgressProtos.internal_static_WorkerReportTaskProgressRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest.class,
                            com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest.Builder.class);
        }

        public static com.google.protobuf.Parser<WorkerReportTaskProgressRequest> PARSER = new com.google.protobuf.AbstractParser<WorkerReportTaskProgressRequest>() {
            public WorkerReportTaskProgressRequest parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                return new WorkerReportTaskProgressRequest(input, extensionRegistry);
            }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<WorkerReportTaskProgressRequest> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int FULL_ID_FIELD_NUMBER = 1;
        private java.lang.Object fullId_;

        /**
         * <code>required string full_id = 1;</code>
         */
        public boolean hasFullId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required string full_id = 1;</code>
         */
        public java.lang.String getFullId() {
            java.lang.Object ref = fullId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    fullId_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string full_id = 1;</code>
         */
        public com.google.protobuf.ByteString getFullIdBytes() {
            java.lang.Object ref = fullId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                fullId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int PROGRESS_FIELD_NUMBER = 2;
        private float progress_;

        /**
         * <code>required float progress = 2;</code>
         */
        public boolean hasProgress() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required float progress = 2;</code>
         */
        public float getProgress() {
            return progress_;
        }

        private void initFields() {
            fullId_ = "";
            progress_ = 0F;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            if (!hasFullId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasProgress()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getFullIdBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeFloat(2, progress_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, getFullIdBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream.computeFloatSize(2, progress_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest parseFrom(
                com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest parseFrom(
                com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest parseDelimitedFrom(
                java.io.InputStream input) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest parseDelimitedFrom(
                java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest parseFrom(
                com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest parseFrom(
                com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code WorkerReportTaskProgressRequest}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:WorkerReportTaskProgressRequest)
                com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.mogujie.jarvis.protocol.ReportTaskProgressProtos.internal_static_WorkerReportTaskProgressRequest_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.mogujie.jarvis.protocol.ReportTaskProgressProtos.internal_static_WorkerReportTaskProgressRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest.class,
                                com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest.Builder.class);
            }

            // Construct using
            // com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                fullId_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                progress_ = 0F;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.mogujie.jarvis.protocol.ReportTaskProgressProtos.internal_static_WorkerReportTaskProgressRequest_descriptor;
            }

            public com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest getDefaultInstanceForType() {
                return com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest.getDefaultInstance();
            }

            public com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest build() {
                com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest buildPartial() {
                com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest result = new com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest(
                        this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.fullId_ = fullId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.progress_ = progress_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest) {
                    return mergeFrom((com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest other) {
                if (other == com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest.getDefaultInstance())
                    return this;
                if (other.hasFullId()) {
                    bitField0_ |= 0x00000001;
                    fullId_ = other.fullId_;
                    onChanged();
                }
                if (other.hasProgress()) {
                    setProgress(other.getProgress());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasFullId()) {

                    return false;
                }
                if (!hasProgress()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.mogujie.jarvis.protocol.ReportTaskProgressProtos.WorkerReportTaskProgressRequest) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private java.lang.Object fullId_ = "";

            /**
             * <code>required string full_id = 1;</code>
             */
            public boolean hasFullId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required string full_id = 1;</code>
             */
            public java.lang.String getFullId() {
                java.lang.Object ref = fullId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        fullId_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string full_id = 1;</code>
             */
            public com.google.protobuf.ByteString getFullIdBytes() {
                java.lang.Object ref = fullId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    fullId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string full_id = 1;</code>
             */
            public Builder setFullId(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                fullId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string full_id = 1;</code>
             */
            public Builder clearFullId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                fullId_ = getDefaultInstance().getFullId();
                onChanged();
                return this;
            }

            /**
             * <code>required string full_id = 1;</code>
             */
            public Builder setFullIdBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                fullId_ = value;
                onChanged();
                return this;
            }

            private float progress_;

            /**
             * <code>required float progress = 2;</code>
             */
            public boolean hasProgress() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required float progress = 2;</code>
             */
            public float getProgress() {
                return progress_;
            }

            /**
             * <code>required float progress = 2;</code>
             */
            public Builder setProgress(float value) {
                bitField0_ |= 0x00000002;
                progress_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required float progress = 2;</code>
             */
            public Builder clearProgress() {
                bitField0_ = (bitField0_ & ~0x00000002);
                progress_ = 0F;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:WorkerReportTaskProgressRequest)
        }

        static {
            defaultInstance = new WorkerReportTaskProgressRequest(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:WorkerReportTaskProgressRequest)
    }

    public interface ServerReportTaskProgressResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ServerReportTaskProgressResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required bool success = 1;</code>
         */
        boolean hasSuccess();

        /**
         * <code>required bool success = 1;</code>
         */
        boolean getSuccess();

        /**
         * <code>optional string message = 2 [default = ""];</code>
         */
        boolean hasMessage();

        /**
         * <code>optional string message = 2 [default = ""];</code>
         */
        java.lang.String getMessage();

        /**
         * <code>optional string message = 2 [default = ""];</code>
         */
        com.google.protobuf.ByteString getMessageBytes();
    }

    /**
     * Protobuf type {@code ServerReportTaskProgressResponse}
     */
    public static final class ServerReportTaskProgressResponse extends com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:ServerReportTaskProgressResponse)
            ServerReportTaskProgressResponseOrBuilder {
        // Use ServerReportTaskProgressResponse.newBuilder() to construct.
        private ServerReportTaskProgressResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private ServerReportTaskProgressResponse(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final ServerReportTaskProgressResponse defaultInstance;

        public static ServerReportTaskProgressResponse getDefaultInstance() {
            return defaultInstance;
        }

        public ServerReportTaskProgressResponse getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private ServerReportTaskProgressResponse(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            success_ = input.readBool();
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            message_ = bs;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.mogujie.jarvis.protocol.ReportTaskProgressProtos.internal_static_ServerReportTaskProgressResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.mogujie.jarvis.protocol.ReportTaskProgressProtos.internal_static_ServerReportTaskProgressResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse.class,
                            com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse.Builder.class);
        }

        public static com.google.protobuf.Parser<ServerReportTaskProgressResponse> PARSER = new com.google.protobuf.AbstractParser<ServerReportTaskProgressResponse>() {
            public ServerReportTaskProgressResponse parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                return new ServerReportTaskProgressResponse(input, extensionRegistry);
            }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<ServerReportTaskProgressResponse> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int SUCCESS_FIELD_NUMBER = 1;
        private boolean success_;

        /**
         * <code>required bool success = 1;</code>
         */
        public boolean hasSuccess() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required bool success = 1;</code>
         */
        public boolean getSuccess() {
            return success_;
        }

        public static final int MESSAGE_FIELD_NUMBER = 2;
        private java.lang.Object message_;

        /**
         * <code>optional string message = 2 [default = ""];</code>
         */
        public boolean hasMessage() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional string message = 2 [default = ""];</code>
         */
        public java.lang.String getMessage() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    message_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string message = 2 [default = ""];</code>
         */
        public com.google.protobuf.ByteString getMessageBytes() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            success_ = false;
            message_ = "";
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            if (!hasSuccess()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBool(1, success_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getMessageBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeBoolSize(1, success_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, getMessageBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse parseFrom(
                com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse parseFrom(
                com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse parseDelimitedFrom(
                java.io.InputStream input) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse parseDelimitedFrom(
                java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse parseFrom(
                com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse parseFrom(
                com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code ServerReportTaskProgressResponse}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:ServerReportTaskProgressResponse)
                com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.mogujie.jarvis.protocol.ReportTaskProgressProtos.internal_static_ServerReportTaskProgressResponse_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.mogujie.jarvis.protocol.ReportTaskProgressProtos.internal_static_ServerReportTaskProgressResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse.class,
                                com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse.Builder.class);
            }

            // Construct using
            // com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                success_ = false;
                bitField0_ = (bitField0_ & ~0x00000001);
                message_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.mogujie.jarvis.protocol.ReportTaskProgressProtos.internal_static_ServerReportTaskProgressResponse_descriptor;
            }

            public com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse getDefaultInstanceForType() {
                return com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse.getDefaultInstance();
            }

            public com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse build() {
                com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse buildPartial() {
                com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse result = new com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse(
                        this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.success_ = success_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.message_ = message_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse) {
                    return mergeFrom((com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse other) {
                if (other == com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse.getDefaultInstance())
                    return this;
                if (other.hasSuccess()) {
                    setSuccess(other.getSuccess());
                }
                if (other.hasMessage()) {
                    bitField0_ |= 0x00000002;
                    message_ = other.message_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasSuccess()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.mogujie.jarvis.protocol.ReportTaskProgressProtos.ServerReportTaskProgressResponse) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private boolean success_;

            /**
             * <code>required bool success = 1;</code>
             */
            public boolean hasSuccess() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required bool success = 1;</code>
             */
            public boolean getSuccess() {
                return success_;
            }

            /**
             * <code>required bool success = 1;</code>
             */
            public Builder setSuccess(boolean value) {
                bitField0_ |= 0x00000001;
                success_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required bool success = 1;</code>
             */
            public Builder clearSuccess() {
                bitField0_ = (bitField0_ & ~0x00000001);
                success_ = false;
                onChanged();
                return this;
            }

            private java.lang.Object message_ = "";

            /**
             * <code>optional string message = 2 [default = ""];</code>
             */
            public boolean hasMessage() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional string message = 2 [default = ""];</code>
             */
            public java.lang.String getMessage() {
                java.lang.Object ref = message_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        message_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string message = 2 [default = ""];</code>
             */
            public com.google.protobuf.ByteString getMessageBytes() {
                java.lang.Object ref = message_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    message_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string message = 2 [default = ""];</code>
             */
            public Builder setMessage(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                message_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string message = 2 [default = ""];</code>
             */
            public Builder clearMessage() {
                bitField0_ = (bitField0_ & ~0x00000002);
                message_ = getDefaultInstance().getMessage();
                onChanged();
                return this;
            }

            /**
             * <code>optional string message = 2 [default = ""];</code>
             */
            public Builder setMessageBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                message_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:ServerReportTaskProgressResponse)
        }

        static {
            defaultInstance = new ServerReportTaskProgressResponse(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:ServerReportTaskProgressResponse)
    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_WorkerReportTaskProgressRequest_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_WorkerReportTaskProgressRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_ServerReportTaskProgressResponse_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_ServerReportTaskProgressResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        java.lang.String[] descriptorData = { "\n\032report_task_progress.proto\"D\n\037WorkerRe"
                + "portTaskProgressRequest\022\017\n\007full_id\030\001 \002(\t" + "\022\020\n\010progress\030\002 \002(\002\"F\n ServerReportTaskPr"
                + "ogressResponse\022\017\n\007success\030\001 \002(\010\022\021\n\007messa"
                + "ge\030\002 \001(\t:\000B7\n\033com.mogujie.jarvis.protoco" + "lB\030ReportTaskProgressProtos" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
        internal_static_WorkerReportTaskProgressRequest_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_WorkerReportTaskProgressRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_WorkerReportTaskProgressRequest_descriptor, new java.lang.String[] { "FullId", "Progress", });
        internal_static_ServerReportTaskProgressResponse_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_ServerReportTaskProgressResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_ServerReportTaskProgressResponse_descriptor, new java.lang.String[] { "Success", "Message", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
