package com.mogujie.jarvis.dto;

public class JobDependStatus extends JobDependStatusKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_depend_status.preTaskStatus
     *
     * @mbggenerated Thu Sep 10 11:25:15 CST 2015
     */
    private Byte preTaskStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_depend_status.updateUser
     *
     * @mbggenerated Thu Sep 10 11:25:15 CST 2015
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_depend_status.createTime
     *
     * @mbggenerated Thu Sep 10 11:25:15 CST 2015
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_depend_status.updateTime
     *
     * @mbggenerated Thu Sep 10 11:25:15 CST 2015
     */
    private Integer updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_depend_status.preTaskStatus
     *
     * @return the value of job_depend_status.preTaskStatus
     *
     * @mbggenerated Thu Sep 10 11:25:15 CST 2015
     */
    public Byte getPreTaskStatus() {
        return preTaskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_depend_status.preTaskStatus
     *
     * @param preTaskStatus the value for job_depend_status.preTaskStatus
     *
     * @mbggenerated Thu Sep 10 11:25:15 CST 2015
     */
    public void setPreTaskStatus(Byte preTaskStatus) {
        this.preTaskStatus = preTaskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_depend_status.updateUser
     *
     * @return the value of job_depend_status.updateUser
     *
     * @mbggenerated Thu Sep 10 11:25:15 CST 2015
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_depend_status.updateUser
     *
     * @param updateUser the value for job_depend_status.updateUser
     *
     * @mbggenerated Thu Sep 10 11:25:15 CST 2015
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_depend_status.createTime
     *
     * @return the value of job_depend_status.createTime
     *
     * @mbggenerated Thu Sep 10 11:25:15 CST 2015
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_depend_status.createTime
     *
     * @param createTime the value for job_depend_status.createTime
     *
     * @mbggenerated Thu Sep 10 11:25:15 CST 2015
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_depend_status.updateTime
     *
     * @return the value of job_depend_status.updateTime
     *
     * @mbggenerated Thu Sep 10 11:25:15 CST 2015
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_depend_status.updateTime
     *
     * @param updateTime the value for job_depend_status.updateTime
     *
     * @mbggenerated Thu Sep 10 11:25:15 CST 2015
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }
}