package com.mogujie.jarvis.dto;

import java.io.Serializable;
import java.util.Date;

public class Plan implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.planId
     *
     * @mbggenerated Wed Oct 21 10:28:52 CST 2015
     */
    private Long planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.planDate
     *
     * @mbggenerated Wed Oct 21 10:28:52 CST 2015
     */
    private String planDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.jobId
     *
     * @mbggenerated Wed Oct 21 10:28:52 CST 2015
     */
    private Long jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.createTime
     *
     * @mbggenerated Wed Oct 21 10:28:52 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.updateTime
     *
     * @mbggenerated Wed Oct 21 10:28:52 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plan
     *
     * @mbggenerated Wed Oct 21 10:28:52 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.planId
     *
     * @return the value of plan.planId
     *
     * @mbggenerated Wed Oct 21 10:28:52 CST 2015
     */
    public Long getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.planId
     *
     * @param planId the value for plan.planId
     *
     * @mbggenerated Wed Oct 21 10:28:52 CST 2015
     */
    public void setPlanId(Long planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.planDate
     *
     * @return the value of plan.planDate
     *
     * @mbggenerated Wed Oct 21 10:28:52 CST 2015
     */
    public String getPlanDate() {
        return planDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.planDate
     *
     * @param planDate the value for plan.planDate
     *
     * @mbggenerated Wed Oct 21 10:28:52 CST 2015
     */
    public void setPlanDate(String planDate) {
        this.planDate = planDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.jobId
     *
     * @return the value of plan.jobId
     *
     * @mbggenerated Wed Oct 21 10:28:52 CST 2015
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.jobId
     *
     * @param jobId the value for plan.jobId
     *
     * @mbggenerated Wed Oct 21 10:28:52 CST 2015
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.createTime
     *
     * @return the value of plan.createTime
     *
     * @mbggenerated Wed Oct 21 10:28:52 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.createTime
     *
     * @param createTime the value for plan.createTime
     *
     * @mbggenerated Wed Oct 21 10:28:52 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.updateTime
     *
     * @return the value of plan.updateTime
     *
     * @mbggenerated Wed Oct 21 10:28:52 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.updateTime
     *
     * @param updateTime the value for plan.updateTime
     *
     * @mbggenerated Wed Oct 21 10:28:52 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}