package com.mogujie.jarvis.dto;

import java.io.Serializable;
import java.util.Date;

public class TaskSchedule extends TaskScheduleKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_schedule.scheduleTime
     *
     * @mbggenerated Thu Nov 05 15:09:39 CST 2015
     */
    private Long scheduleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_schedule.createTime
     *
     * @mbggenerated Thu Nov 05 15:09:39 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_schedule
     *
     * @mbggenerated Thu Nov 05 15:09:39 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_schedule.scheduleTime
     *
     * @return the value of task_schedule.scheduleTime
     *
     * @mbggenerated Thu Nov 05 15:09:39 CST 2015
     */
    public Long getScheduleTime() {
        return scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_schedule.scheduleTime
     *
     * @param scheduleTime the value for task_schedule.scheduleTime
     *
     * @mbggenerated Thu Nov 05 15:09:39 CST 2015
     */
    public void setScheduleTime(Long scheduleTime) {
        this.scheduleTime = scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_schedule.createTime
     *
     * @return the value of task_schedule.createTime
     *
     * @mbggenerated Thu Nov 05 15:09:39 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_schedule.createTime
     *
     * @param createTime the value for task_schedule.createTime
     *
     * @mbggenerated Thu Nov 05 15:09:39 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}