package com.mogujie.jarvis.dto;

import java.util.Date;

public class WorkerGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker_group.wgroupId
     *
     * @mbggenerated Fri Sep 11 17:27:51 CST 2015
     */
    private Integer wgroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker_group.wgroupName
     *
     * @mbggenerated Fri Sep 11 17:27:51 CST 2015
     */
    private String wgroupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker_group.createTime
     *
     * @mbggenerated Fri Sep 11 17:27:51 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker_group.updateTime
     *
     * @mbggenerated Fri Sep 11 17:27:51 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker_group.wgroupId
     *
     * @return the value of worker_group.wgroupId
     *
     * @mbggenerated Fri Sep 11 17:27:51 CST 2015
     */
    public Integer getWgroupId() {
        return wgroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker_group.wgroupId
     *
     * @param wgroupId the value for worker_group.wgroupId
     *
     * @mbggenerated Fri Sep 11 17:27:51 CST 2015
     */
    public void setWgroupId(Integer wgroupId) {
        this.wgroupId = wgroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker_group.wgroupName
     *
     * @return the value of worker_group.wgroupName
     *
     * @mbggenerated Fri Sep 11 17:27:51 CST 2015
     */
    public String getWgroupName() {
        return wgroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker_group.wgroupName
     *
     * @param wgroupName the value for worker_group.wgroupName
     *
     * @mbggenerated Fri Sep 11 17:27:51 CST 2015
     */
    public void setWgroupName(String wgroupName) {
        this.wgroupName = wgroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker_group.createTime
     *
     * @return the value of worker_group.createTime
     *
     * @mbggenerated Fri Sep 11 17:27:51 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker_group.createTime
     *
     * @param createTime the value for worker_group.createTime
     *
     * @mbggenerated Fri Sep 11 17:27:51 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker_group.updateTime
     *
     * @return the value of worker_group.updateTime
     *
     * @mbggenerated Fri Sep 11 17:27:51 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker_group.updateTime
     *
     * @param updateTime the value for worker_group.updateTime
     *
     * @mbggenerated Fri Sep 11 17:27:51 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}