package com.mogujie.jarvis.dao;

import com.mogujie.jarvis.dto.PlanDependStatus;
import com.mogujie.jarvis.dto.PlanDependStatusExample;
import com.mogujie.jarvis.dto.PlanDependStatusKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlanDependStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan_depend_status
     *
     * @mbggenerated Thu Oct 22 11:03:10 CST 2015
     */
    int countByExample(PlanDependStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan_depend_status
     *
     * @mbggenerated Thu Oct 22 11:03:10 CST 2015
     */
    int deleteByExample(PlanDependStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan_depend_status
     *
     * @mbggenerated Thu Oct 22 11:03:10 CST 2015
     */
    int deleteByPrimaryKey(PlanDependStatusKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan_depend_status
     *
     * @mbggenerated Thu Oct 22 11:03:10 CST 2015
     */
    int insert(PlanDependStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan_depend_status
     *
     * @mbggenerated Thu Oct 22 11:03:10 CST 2015
     */
    int insertSelective(PlanDependStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan_depend_status
     *
     * @mbggenerated Thu Oct 22 11:03:10 CST 2015
     */
    List<PlanDependStatus> selectByExample(PlanDependStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan_depend_status
     *
     * @mbggenerated Thu Oct 22 11:03:10 CST 2015
     */
    PlanDependStatus selectByPrimaryKey(PlanDependStatusKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan_depend_status
     *
     * @mbggenerated Thu Oct 22 11:03:10 CST 2015
     */
    int updateByExampleSelective(@Param("record") PlanDependStatus record, @Param("example") PlanDependStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan_depend_status
     *
     * @mbggenerated Thu Oct 22 11:03:10 CST 2015
     */
    int updateByExample(@Param("record") PlanDependStatus record, @Param("example") PlanDependStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan_depend_status
     *
     * @mbggenerated Thu Oct 22 11:03:10 CST 2015
     */
    int updateByPrimaryKeySelective(PlanDependStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan_depend_status
     *
     * @mbggenerated Thu Oct 22 11:03:10 CST 2015
     */
    int updateByPrimaryKey(PlanDependStatus record);
}