package com.mogujie.jarvis.dao;

import com.mogujie.jarvis.dto.TaskSchedule;
import com.mogujie.jarvis.dto.TaskScheduleExample;
import com.mogujie.jarvis.dto.TaskScheduleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_schedule
     *
     * @mbggenerated Mon Nov 16 16:37:21 CST 2015
     */
    int countByExample(TaskScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_schedule
     *
     * @mbggenerated Mon Nov 16 16:37:21 CST 2015
     */
    int deleteByExample(TaskScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_schedule
     *
     * @mbggenerated Mon Nov 16 16:37:21 CST 2015
     */
    int deleteByPrimaryKey(TaskScheduleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_schedule
     *
     * @mbggenerated Mon Nov 16 16:37:21 CST 2015
     */
    int insert(TaskSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_schedule
     *
     * @mbggenerated Mon Nov 16 16:37:21 CST 2015
     */
    int insertSelective(TaskSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_schedule
     *
     * @mbggenerated Mon Nov 16 16:37:21 CST 2015
     */
    List<TaskSchedule> selectByExample(TaskScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_schedule
     *
     * @mbggenerated Mon Nov 16 16:37:21 CST 2015
     */
    TaskSchedule selectByPrimaryKey(TaskScheduleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_schedule
     *
     * @mbggenerated Mon Nov 16 16:37:21 CST 2015
     */
    int updateByExampleSelective(@Param("record") TaskSchedule record, @Param("example") TaskScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_schedule
     *
     * @mbggenerated Mon Nov 16 16:37:21 CST 2015
     */
    int updateByExample(@Param("record") TaskSchedule record, @Param("example") TaskScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_schedule
     *
     * @mbggenerated Mon Nov 16 16:37:21 CST 2015
     */
    int updateByPrimaryKeySelective(TaskSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_schedule
     *
     * @mbggenerated Mon Nov 16 16:37:21 CST 2015
     */
    int updateByPrimaryKey(TaskSchedule record);
}