package com.mogujie.jarvis.dao;

import com.mogujie.jarvis.dto.WorkerGroupRelation;
import com.mogujie.jarvis.dto.WorkerGroupRelationExample;
import com.mogujie.jarvis.dto.WorkerGroupRelationKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkerGroupRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker_group_relation
     *
     * @mbggenerated Thu Sep 17 14:44:55 CST 2015
     */
    int countByExample(WorkerGroupRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker_group_relation
     *
     * @mbggenerated Thu Sep 17 14:44:55 CST 2015
     */
    int deleteByExample(WorkerGroupRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker_group_relation
     *
     * @mbggenerated Thu Sep 17 14:44:55 CST 2015
     */
    int deleteByPrimaryKey(WorkerGroupRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker_group_relation
     *
     * @mbggenerated Thu Sep 17 14:44:55 CST 2015
     */
    int insert(WorkerGroupRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker_group_relation
     *
     * @mbggenerated Thu Sep 17 14:44:55 CST 2015
     */
    int insertSelective(WorkerGroupRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker_group_relation
     *
     * @mbggenerated Thu Sep 17 14:44:55 CST 2015
     */
    List<WorkerGroupRelation> selectByExample(WorkerGroupRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker_group_relation
     *
     * @mbggenerated Thu Sep 17 14:44:55 CST 2015
     */
    WorkerGroupRelation selectByPrimaryKey(WorkerGroupRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker_group_relation
     *
     * @mbggenerated Thu Sep 17 14:44:55 CST 2015
     */
    int updateByExampleSelective(@Param("record") WorkerGroupRelation record, @Param("example") WorkerGroupRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker_group_relation
     *
     * @mbggenerated Thu Sep 17 14:44:55 CST 2015
     */
    int updateByExample(@Param("record") WorkerGroupRelation record, @Param("example") WorkerGroupRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker_group_relation
     *
     * @mbggenerated Thu Sep 17 14:44:55 CST 2015
     */
    int updateByPrimaryKeySelective(WorkerGroupRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker_group_relation
     *
     * @mbggenerated Thu Sep 17 14:44:55 CST 2015
     */
    int updateByPrimaryKey(WorkerGroupRelation record);
}